//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioShredderInfinite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BioShredderInfinite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your weapons always have ammo, and you never need to reload them..
        /// </summary>
        public static string strChkCheatDescriptionAmmoHack {
            get {
                return ResourceManager.GetString("strChkCheatDescriptionAmmoHack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your HP never reaches zero..
        /// </summary>
        public static string strChkCheatDescriptionHPHack {
            get {
                return ResourceManager.GetString("strChkCheatDescriptionHPHack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lockpick anything, even if you don&apos;t have lockpicks (just ask Elizabeth and she&apos;ll ALWAYS do it)..
        /// </summary>
        public static string strChkCheatDescriptionLockpicksHack {
            get {
                return ResourceManager.GetString("strChkCheatDescriptionLockpicksHack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be rich whenever you use a Vending Machine..
        /// </summary>
        public static string strChkCheatDescriptionMoneyHack {
            get {
                return ResourceManager.GetString("strChkCheatDescriptionMoneyHack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to salts never decrease (if salts are low, just try to use them TWICE to refill)..
        /// </summary>
        public static string strChkCheatDescriptionSaltsHack {
            get {
                return ResourceManager.GetString("strChkCheatDescriptionSaltsHack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMMO hack:.
        /// </summary>
        public static string strChkCheatPromptAmmoHack {
            get {
                return ResourceManager.GetString("strChkCheatPromptAmmoHack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP hack:.
        /// </summary>
        public static string strChkCheatPromptHPHack {
            get {
                return ResourceManager.GetString("strChkCheatPromptHPHack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCKPICK hack:.
        /// </summary>
        public static string strChkCheatPromptLockpicksHack {
            get {
                return ResourceManager.GetString("strChkCheatPromptLockpicksHack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONEY hack:.
        /// </summary>
        public static string strChkCheatPromptMoneyHack {
            get {
                return ResourceManager.GetString("strChkCheatPromptMoneyHack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALTS hack:.
        /// </summary>
        public static string strChkCheatPromptSaltsHack {
            get {
                return ResourceManager.GetString("strChkCheatPromptSaltsHack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheats.
        /// </summary>
        public static string strGroupBoxHeaderCheats {
            get {
                return ResourceManager.GetString("strGroupBoxHeaderCheats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game info.
        /// </summary>
        public static string strGroupBoxHeaderGameInfo {
            get {
                return ResourceManager.GetString("strGroupBoxHeaderGameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support us!.
        /// </summary>
        public static string strGroupBoxHeaderSupport {
            get {
                return ResourceManager.GetString("strGroupBoxHeaderSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Click to donate via PayPal)..
        /// </summary>
        public static string strLblClickToDonate {
            get {
                return ResourceManager.GetString("strLblClickToDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game&apos;s process:.
        /// </summary>
        public static string strLblGamesProcessPrompt {
            get {
                return ResourceManager.GetString("strLblGamesProcessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not attached....
        /// </summary>
        public static string strLblNotAttached {
            get {
                return ResourceManager.GetString("strLblNotAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, consider supporting the developer!.
        /// </summary>
        public static string strLblRequestForDonation {
            get {
                return ResourceManager.GetString("strLblRequestForDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required game version:.
        /// </summary>
        public static string strLblRequiredGameVersionPrompt {
            get {
                return ResourceManager.GetString("strLblRequiredGameVersionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.1643565.
        /// </summary>
        public static string strLblRequiredGameVersionValue {
            get {
                return ResourceManager.GetString("strLblRequiredGameVersionValue", resourceCulture);
            }
        }
    }
}
